name: Build and Push Docker image to Docker Hub

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Clone ton dépôt
      - name: Checkout repository
        uses: actions/checkout@v4

      # Connexion à Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Builder et tagger l’image
      - name: Build and tag Docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/chrome
          docker build -t $IMAGE_NAME:0.0.1 .
          docker tag $IMAGE_NAME:0.0.1 $IMAGE_NAME:latest

      # Pousser vers Docker Hub
      - name: Push image to Docker Hub
        run: |
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/chrome
          docker push $IMAGE_NAME:0.0.1
          docker push $IMAGE_NAME:latest